name: Publish docker image on merge to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: basisai/python-alpine-grpcio
          tags: latest
