name: Publish docker image on merge to master

on:
  push:
    # Matching tags: 3.8.2-1.30.0, etc.
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths:
      - Dockerfile
      - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2.2.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          repository: quay.io/basisai/python-alpine-grpcio
          tag_with_ref: true
          # Only push the image on new tag event
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
