name: Publish docker image on merge to master

on:
  push:
    branches:
      - master
    # Matching tags: 3.9.7-1.14-1.41.1, etc.
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths:
      - Dockerfile
      - requirements.txt

jobs:
  build:
    runs-on: [self-hosted, docker, integration]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/basisai/python-alpine-grpcio # list of Docker images to use as base name for tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Quay
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          outputs: type=docker,dest=/tmp/python-alpine-grpcio-${{ github.sha }}.tar
      - name: Build and push
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Upload artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: /tmp/python-alpine-grpcio-${{ github.sha }}.tar
          retention-days: 1

  scan:
    runs-on: [self-hosted, docker, integration]
    needs: build
    strategy:
      matrix:
        include:
          - severity: "MEDIUM,HIGH"
            exit-code: "0"
          - severity: "CRITICAL"
            exit-code: "1"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: tmp
      - name: Run Trivy vulnerability scanner for ${{ matrix.severity }} severity
        if: ${{ github.event_name == 'pull_request' }}
        uses: aquasecurity/trivy-action@master
        with:
          input: tmp/python-alpine-grpcio-${{ github.sha }}.tar
          format: 'table'
          exit-code: ${{ matrix.exit-code }}
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: ${{ matrix.severity }}
      - name: Run Trivy vulnerability scanner for ${{ matrix.severity }} severity
        if: ${{ github.event_name != 'pull_request' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.docker_meta.outputs.tags }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-${{ matrix.severity }}.sarif'
          exit-code: ${{ matrix.exit-code }}
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: ${{ matrix.severity }}
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-${{ matrix.severity }}.sarif'
