name: Publish docker image on merge to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: |
          PYTHON_VERSION=$(python --version | cut -d " " -f 2)
          GRPC_VERSION=$(pip show grpcio | grep -i version | cut -d " " -f 2)
          TAG="${PYTHON_VERSION}-${GRPC_VERSION}"
          git tag "${TAG}"
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" refs/tags/"${tag}"
